openapi: 3.1.0

info:
  title: Electronic Trading API
  version: 1.0.0
  description: >
    A RESTful API for a simplified electronic trading platform.

servers:
  - url: https://api.example.com/v1
    description: Example production server

paths:
  /orders:
    post:
      summary: Submit new order
      description: Creates a new buy or sell order for a financial instrument.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - symbol
                - side
                - type
                - quantity
                
              properties:
                symbol:
                  type: string
                  example: AAPL
                  
                side:
                  type: string
                  enum:
                    - buy
                    - sell
                    
                type:
                  type: string
                  enum:
                    - market
                    - limit
                    
                quantity:
                  type: integer
                  minimum: 1
                  example: 100
                  
                limit_price:
                  type: number
                  exclusiveMinimum: 0
                  example: 220.00

              if:
                properties:
                  type:
                    const: limit

              then:
                required:
                  - limit_price


      responses:
        '201':
          description: Order successfully created.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: ord_8f72a1

                  symbol:
                    type: string
                    example: AAPL

                  side:
                    type: string
                    enum:
                      - buy
                      - sell

                  type:
                    type: string
                    enum:
                      - market
                      - limit

                  quantity:
                    type: integer
                    example: 100

                  limit_price:
                    type:
                      - number
                      - "null"
                    example: 220.00

                  filled_quantity:
                    type: integer
                    example: 0

                  status:
                    type: string
                    enum:
                      - open
                      - partially_filled
                      - filled
                      - cancelled

                  created_at:
                    type: string
                    format: date-time
                    example: "2026-08-17T22:02:00Z"
